wandb:
  project: lhf-1d #lhf-alignment
  artifact_name: data
  artifact_version: v91 #v85 #latest
  artifact_type: data

analysis:
  iteration: 0
  vis_m: 32
  seed: 0

visualization:
  ylim: [-1, 5]
  scale: free
