method: grid

command:
  - ${env}
  - python
  - notebooks/pipeline.py

parameters:
  target_manifold:
    values:
      - name: close
        alpha: 0.5
        beta: 0.5
        gamma: 0.0

      - name: neutral
        alpha: 1.0
        beta: 0.5
        gamma: 0.0

      - name: far
        alpha: 0.7
        beta: 0.1
        gamma: 0.0

  creativity-incentive:
    values:
     - var-target
     - max-var
     - none

  pre_train_features:
    values:
      - [256,256]
      - [64,64]
      - [32,32]
  
