method: grid

command:
  - ${env}
  - python
  - notebooks/pipeline.py

parameters:
  N:
    values:
      - 2
      - 5
      - 10

  u_type:
    values:
      - flock
      - zigzag
      - close
  
